# Generated by Django 2.2.6 on 2019-10-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Amigo')),
                ('nome_mae', models.CharField(max_length=50, verbose_name='Nome da mãe')),
                ('telefone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('grupo_amigo', models.CharField(choices=[('Prédio', 'Prédio'), ('Escola', 'Escola')], default='', max_length=100, verbose_name='Grupo do amigo')),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Colecão',
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.IntegerField(verbose_name='Número da edição')),
                ('ano', models.IntegerField(verbose_name='Ano de lançamento')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_emprestimos.Colecao', verbose_name='Coleção')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data de emprestimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de devolução')),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_emprestimos.Amigo')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_emprestimos.Revista')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_emprestimos.Revista')),
            ],
        ),
    ]
